# Generated by Django 5.1.2 on 2024-12-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gdesc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.book')),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.genre')),
            ],
            options={
                'unique_together': {('bid', 'gname')},
            },
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.book')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.publisher')),
            ],
            options={
                'unique_together': {('bid', 'pid')},
            },
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.author')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.book')),
            ],
            options={
                'unique_together': {('bid', 'aid')},
            },
        ),
    ]
