# Generated by Django 5.1.2 on 2024-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_user_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='btitle',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='gname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
