# Generated by Django 5.1.2 on 2024-12-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_alter_author_aname_alter_book_btitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='aid',
            new_name='AuthorID',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='aname',
            new_name='AuthorName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bid',
            new_name='BookID',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='btitle',
            new_name='BookTitle',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uid',
            new_name='UserID',
        ),
        migrations.RenameField(
            model_name='contains',
            old_name='bid',
            new_name='BookID',
        ),
        migrations.RenameField(
            model_name='contains',
            old_name='gname',
            new_name='GenreName',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='gid',
            new_name='GenreID',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='gname',
            new_name='GenreName',
        ),
        migrations.RenameField(
            model_name='published',
            old_name='bid',
            new_name='BookID',
        ),
        migrations.RenameField(
            model_name='published',
            old_name='pid',
            new_name='PublisherID',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pid',
            new_name='PublisherID',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pname',
            new_name='PublisherName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='UserID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='UserName',
        ),
        migrations.RenameField(
            model_name='written',
            old_name='aid',
            new_name='AuthorID',
        ),
        migrations.RenameField(
            model_name='written',
            old_name='bid',
            new_name='BookID',
        ),
        migrations.AlterUniqueTogether(
            name='contains',
            unique_together={('BookID', 'GenreName')},
        ),
        migrations.AlterUniqueTogether(
            name='published',
            unique_together={('BookID', 'PublisherID')},
        ),
        migrations.AlterUniqueTogether(
            name='written',
            unique_together={('BookID', 'AuthorID')},
        ),
    ]
