# Generated by Django 5.1.2 on 2024-12-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_rename_aid_author_authorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.user'),
        ),
    ]
