# Generated by Django 5.1.2 on 2024-12-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_book_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='AuthorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.author'),
        ),
    ]
