# Generated by Django 5.1.2 on 2024-12-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_book_authorid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Written',
            new_name='Book_and_Authors',
        ),
        migrations.RenameModel(
            old_name='Contains',
            new_name='Book_and_Genres',
        ),
        migrations.RenameModel(
            old_name='Published',
            new_name='Book_and_Publishers',
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Book_Authors',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Book_Genres',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Book_List',
        ),
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Book_Publishers',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='list_of_registered_users',
        ),
    ]
